### PR TITLE
Disable all auto-downloads

### PR DESCRIPTION
**Pull request by mooomooo**
Update the preferences UI to have all sources de-selected by default (#10 )

### CODE REVIEW

**Comment by yourealwaysbe** [comment]
Cool, thanks for this!

I'll apologise in advance for taking a while to look at this properly -- been a bit busy lately, but will get to it when i can.

**Comment by yourealwaysbe** [comment]
Actually, this change doesn't turn off auto-downloads. That is already false by default. This disables all downloaders, meaning new users will be presented with no possible downloads until they've gone into the settings to enable some.

What's the reasoning for requiring users to change the default settings before they can make any downloads?

**Comment by mooomooo** [comment]
Oh hm I see the distinction now.  My use case has been that I do want automatic downloads, but only from a small number of sources (1), so I'd have to turn all the existing options off before turning on auto-download.  I suppose if the primary use case is to manually download individual puzzles / dates, then it would be nice to have all the options presented in the Download Puzzles dialog as it currently is.

I hadn't considered that latter option, so I'm happy to drop this MR.  I wonder if it makes sense to separate an auto-download toggle from a show-in-list toggle, but that's a bigger task for another day.

**Comment by yourealwaysbe** [comment]
This makes sense -- naively the puzzle settings could be changed from on/off to on/off/auto. I think then it gets harder to see at a glance what's selected and what's not, but i expect this is not too hard to work around. I'll have a look.

**Pull request closed without merging**
