### PR TITLE
Dashes support and more french sources

### PR DESCRIPTION
**Pull request by slock83**
Hello,

Thanks for maintaining this app ! I recently noticed that the dashes were missing in french crosswords, so I added support for them (not the best implementation, but I didn't want to reimplement half the renderer just for that).

I also added a few more sources for french crossword (I could find much more, but I don't want to clutter the downloader too much)

I also fixed parsing the clues in some rare cases (clue refers only accross, but directly bellow box).

Thanks !

### CODE REVIEW

**Comment by yourealwaysbe** [comment]
Awesome, thanks for the work!

I'm slightly ahead of you ([here]( https://github.com/yourealwaysbe/forkyz/commit/e3ab96176c48a3006259e403fa2ad985b36a3e09) and [here]( https://github.com/yourealwaysbe/forkyz/commit/a72100a48384202d0c021cfbd0b763c79cbb0335)) with the dashes, so there'll be something to do to make it compatible with the current [version 39 branch](https://github.com/yourealwaysbe/forkyz/commits/version39). I have some time tonight and it looks like fairly light adjustments.

Thanks for the downloaders too. Looks good at a glance, though the share and source URLs need adjusting. I'll tweak that tonight as well.

**Comment by yourealwaysbe** [comment]
Btw, i noticed the dashes when implementing the Le Parisien reader, but couldn't figure out how they were represented in the data format. Thanks for solving that mystery :)

**Comment by yourealwaysbe** [comment]
Oh, should the dashes be dots? (Both are now supported.)

**Comment by slock83** [comment]
Yes your implementation seems much cleaner (It's been a while since I've used java), I planed on adding dotted support too and on cleaning things up at that point, but hadn't seen the v39 branch, my bad ...

And I get why you didn't figure out the format when you implemented the reader initially : the implementation is bugged on the web player ... In french we usually use dashes to represent multi part clues (two words) or some acronyms, so I just used that and suddenly the coordinates made sense :)

As for the dots, I believe we mostly use dashes for this, so dashes are fine.

**Comment by yourealwaysbe** [comment]
> but hadn't seen the v39 branch, my bad ...

I'm not sure you'd want to try to develop against that branch anyway. I keep rebasing and force-pushing when i change my mind about something, realise i've forgotten a file, merge WIP commits, &c.

> And I get why you didn't figure out the format when you implemented the reader initially : the implementation is bugged on the web player

Aha!

**Comment by yourealwaysbe** [comment]
I've merged the changes in now ([here](https://github.com/yourealwaysbe/forkyz/commit/8f31e37d4a5cc4f536af430e5ad40f0a68a66ab2) and [here](https://github.com/yourealwaysbe/forkyz/commit/5aba0e3e456b4f48ce719e00cad9de12ddfdfe1c)). I tweaked the code a bit to fit the coding style.

These crosswords also answer a question i had about whether dotted/dashed bars should mark the end of words :)

Thanks!

**Comment by yourealwaysbe** [comment]
I've [removed](https://github.com/yourealwaysbe/forkyz/commit/f87383a0b9c87961e02b80dff2590e5123e258ed) the Notre Temps Geant Force 2 puzzle source. It was originally down as being weekly on Saturdays. However, it's actually every 9-10 days, which makes it unpredictable (and broken for anything other than the base date).

I think it would be better as a [PageScraper](https://github.com/yourealwaysbe/forkyz/blob/master/app/src/main/java/app/crossword/yourealwaysbe/net/PageScraper.java) that would scrape the puzzle numbers from the [puzzle page](https://www.notretemps.com/jeux/jeux-en-ligne/mots-fleches-geants/force-2/) and download the most recent that hasn't been downloaded already.

You'd probably need a NotreTemps subclass of PageScraper, overriding the getPuzzleURLs so it can scrape for puzzle numbers and then return the urls to the data files. Plus maybe other tweaks to make it nice.

**Comment by yourealwaysbe** [comment]
The current working branch is [version41](https://github.com/yourealwaysbe/forkyz/tree/version41/app/src/main/java/app/crossword/yourealwaysbe/net). I'll probably release that soon.

**Comment by yourealwaysbe** [comment]
Version 41 is now in master. If i don't start a version42 in the next week, i won't start one until late April.

**Pull request closed without merging**
